workspace:
  base: /ramdisk
  path: /mkinitramfs
pipeline:
  build:
    image: dvitali/android-build:feb-20
    commands:
      - "./mkinitramfs.sh -d mmcblk0p4 -s / -o initramfs_system.cpio"
      - "./mkinitramfs.sh -d mmcblk0p7 -s / -o initramfs_data.cpio"
      - "./mkinitramfs.sh -d mmcblk0p7 -s /rootfs -o initramfs_data_distro.cpio"
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: /ramdisk/mkinitramfs/*.img
    when:
      event: tag
